In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

In [2]:
df_import = pd.read_csv("db.csv", sep=";")

df_concessionaire = pd.DataFrame(df_import)

In [3]:
df_concessionaire

,Nombre,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Llantas de aleación', 'Cerraduras electricas...",88078.64
1,Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94
2,Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Control de estabilidad'...",72832.16
3,DS5,Motor 2.4 Turbo,2019,NaN,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07
4,Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Llantas de aleación', '4 X 4', 'Central mult...",92612.10
...,...,...,...,...,...,...,...
253,Phantom 2013,Motor V8,2014,27505.0,False,"['Control de estabilidad', 'Piloto automático'...",51759.58
254,Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Asientos de cuero', 'Panel digital', 'Sensor...",51667.06
255,Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Llantas de aleación', 'Control de tracción',...",68934.03
256,Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Aire condicionado', '4 X 4', 'Transmisión au...",122110.90
257,Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimedia', 'Techo panorámico', 'Ve...",90381.47

Cleaned DataFrame and zeros were added for "Kilometraje"

In [4]:
df_concessionaire.isna().sum()

Nombre          0
Motor           0
Año             0
Kilometraje    61
Cero_km         0
Accesorios      0
Valor           0
dtype: int64

In [5]:
df_clean = df_concessionaire.fillna(0)

df_clean

,Nombre,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Llantas de aleación', 'Cerraduras electricas...",88078.64
1,Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94
2,Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Control de estabilidad'...",72832.16
3,DS5,Motor 2.4 Turbo,2019,0.0,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07
4,Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Llantas de aleación', '4 X 4', 'Central mult...",92612.10
...,...,...,...,...,...,...,...
253,Phantom 2013,Motor V8,2014,27505.0,False,"['Control de estabilidad', 'Piloto automático'...",51759.58
254,Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Asientos de cuero', 'Panel digital', 'Sensor...",51667.06
255,Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Llantas de aleación', 'Control de tracción',...",68934.03
256,Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Aire condicionado', '4 X 4', 'Transmisión au...",122110.90
257,Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimedia', 'Techo panorámico', 'Ve...",90381.47

In [6]:
df_clean.isna().sum()

Nombre         0
Motor          0
Año            0
Kilometraje    0
Cero_km        0
Accesorios     0
Valor          0
dtype: int64

Cleaned and split the column "Accesorios"

In [7]:
df_clean["Accesorios"] = df_clean["Accesorios"].str.replace(r"\[|\]|'", "", regex=True)

df_clean

,Nombre,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"Llantas de aleación, Cerraduras electricas, Pi...",88078.64
1,Passat,Motor Diesel,1991,5712.0,False,"Central multimedia, Techo panorámico, Frenos A...",106161.94
2,Crossfox,Motor Diesel V8,1990,37123.0,False,"Piloto automático, Control de estabilidad, Sen...",72832.16
3,DS5,Motor 2.4 Turbo,2019,0.0,True,"Cerraduras electricas, 4 X 4, Ventanas eléctri...",124549.07
4,Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"Llantas de aleación, 4 X 4, Central multimedia...",92612.10
...,...,...,...,...,...,...,...
253,Phantom 2013,Motor V8,2014,27505.0,False,"Control de estabilidad, Piloto automático, Tra...",51759.58
254,Cadillac Ciel concept,Motor V8,1991,29981.0,False,"Asientos de cuero, Panel digital, Sensor de ll...",51667.06
255,Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"Llantas de aleación, Control de tracción, Tran...",68934.03
256,Aston Martin DB5,Motor Diesel,1996,7685.0,False,"Aire condicionado, 4 X 4, Transmisión automáti...",122110.90
257,Macan,Motor Diesel V6,1992,50188.0,False,"Central multimedia, Techo panorámico, Ventanas...",90381.47

Split the column "Accesorios"

In [8]:
accessories_dummies = df_clean["Accesorios"].str.get_dummies(sep=", ")

accessories_dummies

,4 X 4,Aire condicionado,Asientos de cuero,Central multimedia,Cerraduras electricas,Control de estabilidad,Control de tracción,Cámara de estacionamiento,Frenos ABS,Llantas de aleación,Panel digital,Piloto automático,Sensor crepuscular,Sensor de estacionamiento,Sensor de lluvia,Techo panorámico,Transmisión automática,Ventanas eléctricas
0,0,1,1,0,1,0,0,0,0,1,0,1,1,1,1,0,0,0
1,1,0,1,1,0,0,0,1,1,0,1,1,0,0,0,1,0,0
2,0,0,1,1,0,1,0,0,1,0,0,1,1,0,0,0,1,1
3,1,1,0,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1
4,1,1,0,1,0,1,0,0,0,1,0,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,0,1,0,0,0,1,1,1,0,0,1,1,0,0,0,1,1,0
254,0,0,1,0,1,0,0,0,0,1,1,1,0,1,1,0,0,1
255,1,1,0,1,0,0,1,0,0,1,0,0,1,0,0,1,1,0
256,1,1,0,1,0,0,1,1,1,0,1,0,0,0,0,0,1,0
257,0,0,0,1,1,0,1,1,1,1,0,0,0,0,0,1,0,1

Combine both variables

In [9]:
df_final = pd.concat([df_clean, accessories_dummies], axis=1)

df_final = df_final.drop(columns=["Accesorios"])

df_final.head()

,Nombre,Motor,Año,Kilometraje,Cero_km,Valor,4 X 4,Aire condicionado,Asientos de cuero,Central multimedia,...,Frenos ABS,Llantas de aleación,Panel digital,Piloto automático,Sensor crepuscular,Sensor de estacionamiento,Sensor de lluvia,Techo panorámico,Transmisión automática,Ventanas eléctricas
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,88078.64,0,1,1,0,...,0,1,0,1,1,1,1,0,0,0
1,Passat,Motor Diesel,1991,5712.0,False,106161.94,1,0,1,1,...,1,0,1,1,0,0,0,1,0,0
2,Crossfox,Motor Diesel V8,1990,37123.0,False,72832.16,0,0,1,1,...,1,0,0,1,1,0,0,0,1,1
3,DS5,Motor 2.4 Turbo,2019,0.0,True,124549.07,1,1,0,0,...,0,1,0,0,1,0,1,0,0,1
4,Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,92612.10,1,1,0,1,...,0,1,0,1,0,1,0,0,1,0

In [10]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Nombre                     258 non-null    object
 1   Motor                      258 non-null    object
 2   Año                        258 non-null    int64
 3   Kilometraje                258 non-null    float64
 4   Cero_km                    258 non-null    bool
 5   Valor                      258 non-null    float64
 6   4 X 4                      258 non-null    int64
 7   Aire condicionado          258 non-null    int64
 8   Asientos de cuero          258 non-null    int64
 9   Central multimedia         258 non-null    int64
 10  Cerraduras electricas      258 non-null    int64
 11  Control de estabilidad     258 non-null    int64
 12  Control de tracción        258 non-null    int64
 13  Cámara de estacionamiento  258 non-null    int64
 14  Frenos ABS                 258 non-null    int64
 15  Llantas de aleación        258 non-null    int64
 16  Panel digital              258 non-null    int64
 17  Piloto automático          258 non-null    int64
 18  Sensor crepuscular         258 non-null    int64
 19  Sensor de estacionamiento  258 non-null    int64
 20  Sensor de lluvia           258 non-null    int64
 21  Techo panorámico           258 non-null    int64
 22  Transmisión automática     258 non-null    int64
 23  Ventanas eléctricas        258 non-null    int64
dtypes: bool(1), float64(2), int64(19), object(2)
memory usage: 46.7+ KB

Split the column "Motor"

In [11]:
df_final = pd.get_dummies(df_final, columns=["Motor"])

df_final

,Nombre,Año,Kilometraje,Cero_km,Valor,4 X 4,Aire condicionado,Asientos de cuero,Central multimedia,Cerraduras electricas,...,Motor_Motor 2.0 16v,Motor_Motor 2.4 Turbo,Motor_Motor 3.0 32v,Motor_Motor 4.0 Turbo,Motor_Motor 5.0 V8 Bi-Turbo,Motor_Motor Diesel,Motor_Motor Diesel V6,Motor_Motor Diesel V8,Motor_Motor V6,Motor_Motor V8
0,Jetta Variant,2003,44410.0,False,88078.64,0,1,1,0,1,...,False,False,False,True,False,False,False,False,False,False
1,Passat,1991,5712.0,False,106161.94,1,0,1,1,0,...,False,False,False,False,False,True,False,False,False,False
2,Crossfox,1990,37123.0,False,72832.16,0,0,1,1,0,...,False,False,False,False,False,False,False,True,False,False
3,DS5,2019,0.0,True,124549.07,1,1,0,0,1,...,False,True,False,False,False,False,False,False,False,False
4,Aston Martin DB4,2006,25757.0,False,92612.10,1,1,0,1,0,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Phantom 2013,2014,27505.0,False,51759.58,0,1,0,0,0,...,False,False,False,False,False,False,False,False,False,True
254,Cadillac Ciel concept,1991,29981.0,False,51667.06,0,0,1,0,1,...,False,False,False,False,False,False,False,False,False,True
255,Classe GLK,2002,52637.0,False,68934.03,1,1,0,1,0,...,False,False,False,False,True,False,False,False,False,False
256,Aston Martin DB5,1996,7685.0,False,122110.90,1,1,0,1,0,...,False,False,False,False,False,True,False,False,False,False
257,Macan,1992,50188.0,False,90381.47,0,0,0,1,1,...,False,False,False,False,False,False,True,False,False,False

Delete the column "Nombre"

In [12]:
df_final = df_final.drop(columns="Nombre")

df_final

,Año,Kilometraje,Cero_km,Valor,4 X 4,Aire condicionado,Asientos de cuero,Central multimedia,Cerraduras electricas,Control de estabilidad,...,Motor_Motor 2.0 16v,Motor_Motor 2.4 Turbo,Motor_Motor 3.0 32v,Motor_Motor 4.0 Turbo,Motor_Motor 5.0 V8 Bi-Turbo,Motor_Motor Diesel,Motor_Motor Diesel V6,Motor_Motor Diesel V8,Motor_Motor V6,Motor_Motor V8
0,2003,44410.0,False,88078.64,0,1,1,0,1,0,...,False,False,False,True,False,False,False,False,False,False
1,1991,5712.0,False,106161.94,1,0,1,1,0,0,...,False,False,False,False,False,True,False,False,False,False
2,1990,37123.0,False,72832.16,0,0,1,1,0,1,...,False,False,False,False,False,False,False,True,False,False
3,2019,0.0,True,124549.07,1,1,0,0,1,0,...,False,True,False,False,False,False,False,False,False,False
4,2006,25757.0,False,92612.10,1,1,0,1,0,1,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,2014,27505.0,False,51759.58,0,1,0,0,0,1,...,False,False,False,False,False,False,False,False,False,True
254,1991,29981.0,False,51667.06,0,0,1,0,1,0,...,False,False,False,False,False,False,False,False,False,True
255,2002,52637.0,False,68934.03,1,1,0,1,0,0,...,False,False,False,False,True,False,False,False,False,False
256,1996,7685.0,False,122110.90,1,1,0,1,0,0,...,False,False,False,False,False,True,False,False,False,False
257,1992,50188.0,False,90381.47,0,0,0,1,1,0,...,False,False,False,False,False,False,True,False,False,False

Change bool to int the column "Cero_km"

In [13]:
df_final["Cero_km"] = df_final["Cero_km"].astype(int)

df_final

,Año,Kilometraje,Cero_km,Valor,4 X 4,Aire condicionado,Asientos de cuero,Central multimedia,Cerraduras electricas,Control de estabilidad,...,Motor_Motor 2.0 16v,Motor_Motor 2.4 Turbo,Motor_Motor 3.0 32v,Motor_Motor 4.0 Turbo,Motor_Motor 5.0 V8 Bi-Turbo,Motor_Motor Diesel,Motor_Motor Diesel V6,Motor_Motor Diesel V8,Motor_Motor V6,Motor_Motor V8
0,2003,44410.0,0,88078.64,0,1,1,0,1,0,...,False,False,False,True,False,False,False,False,False,False
1,1991,5712.0,0,106161.94,1,0,1,1,0,0,...,False,False,False,False,False,True,False,False,False,False
2,1990,37123.0,0,72832.16,0,0,1,1,0,1,...,False,False,False,False,False,False,False,True,False,False
3,2019,0.0,1,124549.07,1,1,0,0,1,0,...,False,True,False,False,False,False,False,False,False,False
4,2006,25757.0,0,92612.10,1,1,0,1,0,1,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,2014,27505.0,0,51759.58,0,1,0,0,0,1,...,False,False,False,False,False,False,False,False,False,True
254,1991,29981.0,0,51667.06,0,0,1,0,1,0,...,False,False,False,False,False,False,False,False,False,True
255,2002,52637.0,0,68934.03,1,1,0,1,0,0,...,False,False,False,False,True,False,False,False,False,False
256,1996,7685.0,0,122110.90,1,1,0,1,0,0,...,False,False,False,False,False,True,False,False,False,False
257,1992,50188.0,0,90381.47,0,0,0,1,1,0,...,False,False,False,False,False,False,True,False,False,False

Create X e y

In [14]:
X = df_final.drop(columns=["Valor"])

X

,Año,Kilometraje,Cero_km,4 X 4,Aire condicionado,Asientos de cuero,Central multimedia,Cerraduras electricas,Control de estabilidad,Control de tracción,...,Motor_Motor 2.0 16v,Motor_Motor 2.4 Turbo,Motor_Motor 3.0 32v,Motor_Motor 4.0 Turbo,Motor_Motor 5.0 V8 Bi-Turbo,Motor_Motor Diesel,Motor_Motor Diesel V6,Motor_Motor Diesel V8,Motor_Motor V6,Motor_Motor V8
0,2003,44410.0,0,0,1,1,0,1,0,0,...,False,False,False,True,False,False,False,False,False,False
1,1991,5712.0,0,1,0,1,1,0,0,0,...,False,False,False,False,False,True,False,False,False,False
2,1990,37123.0,0,0,0,1,1,0,1,0,...,False,False,False,False,False,False,False,True,False,False
3,2019,0.0,1,1,1,0,0,1,0,0,...,False,True,False,False,False,False,False,False,False,False
4,2006,25757.0,0,1,1,0,1,0,1,0,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,2014,27505.0,0,0,1,0,0,0,1,1,...,False,False,False,False,False,False,False,False,False,True
254,1991,29981.0,0,0,0,1,0,1,0,0,...,False,False,False,False,False,False,False,False,False,True
255,2002,52637.0,0,1,1,0,1,0,0,1,...,False,False,False,False,True,False,False,False,False,False
256,1996,7685.0,0,1,1,0,1,0,0,1,...,False,False,False,False,False,True,False,False,False,False
257,1992,50188.0,0,0,0,0,1,1,0,1,...,False,False,False,False,False,False,True,False,False,False

In [15]:
y = df_final["Valor"]

y

0       88078.64
1      106161.94
2       72832.16
3      124549.07
4       92612.10
         ...
253     51759.58
254     51667.06
255     68934.03
256    122110.90
257     90381.47
Name: Valor, Length: 258, dtype: float64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

Training the IA

In [17]:
train_forest = RandomForestRegressor(random_state=42)

train_forest.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [18]:
forest_predict = train_forest.predict(X_test)

forest_predict

array([101131.2827,  98164.3247,  89152.5844,  99585.5396,  94574.0932,
       102843.6272, 102074.3201,  95087.5581, 100940.9892,  93200.3765,
        98250.9962,  92700.9587, 102961.4015, 112616.6536,  93450.9446,
        97997.5431,  84738.3471, 102775.7323,  98287.1809,  82359.7629,
        89465.0454, 118912.5261, 109268.2037, 105474.5547,  95490.0833,
        94836.0323, 113790.9626,  93116.9718,  98370.9952, 108749.0628,
       114083.0822,  98367.1814, 100680.0384, 101451.6997, 108140.1938,
        98174.0475, 104110.4778, 102116.644 , 100228.0279, 111739.2714,
       101211.0028,  96292.0004,  80318.7739, 107574.3238,  96269.3406,
       102907.863 ,  90876.5787,  95453.4032,  96016.6729, 111631.4297,
        89550.0309,  97047.4962, 113065.504 ,  93831.1813,  90427.6071,
       109841.1263, 104700.0291, 112818.3909, 115508.0748,  85286.6858,
       100870.6561,  85848.8635, 105389.7662,  98668.5395,  93615.4765])

In [19]:
error_df = mean_absolute_error(y_test, forest_predict)

error_df

29439.731067692304

Option A: Linear Regression

In [20]:
linear_train = LinearRegression()

linear_train.fit(X_train, y_train)

LinearRegression()

In [21]:
linear_predict = linear_train.predict(X_test)

linear_predict

array([ 90023.20587904,  88756.97828947,  89100.14740364, 103155.88754472,
       112765.68263123,  99353.02637585, 100657.87084139,  91891.20607401,
       102570.43485543,  79847.43162058,  80690.21959414,  84390.5972035 ,
       104955.34154379, 103453.71926783, 110201.34961802,  96735.29554202,
        81338.47348437, 117301.20414521, 105391.04314729,  72312.72739714,
        86763.29346605, 126177.11560865, 100199.5504856 ,  92962.10560897,
        91770.22885071, 116113.86117735,  89979.06495052,  92267.87361481,
       103384.97326627,  89986.66064556, 134548.8695768 ,  94461.9607582 ,
       106216.76456814, 107576.4338222 , 124091.67589207,  87405.5915009 ,
       106386.89831437, 116807.56803693, 107317.62966069, 117127.00294064,
       107237.8385443 , 100184.05126024,  75547.76752607,  96455.06728808,
       113558.22352821, 106641.99568877,  86972.66363357,  88016.70678417,
       100742.74310027, 116205.17226351,  88650.2940922 ,  92129.26659804,
        98999.42843293,  82603.64410577,  86666.97694091,  92455.26072647,
        99379.31833411, 113596.40212395, 143525.20516009,  78283.342525  ,
        93098.81324721,  85804.51059504,  98157.8747027 , 112726.00867853,
       103639.08775061])

In [22]:
linear_error = mean_absolute_error(y_test, linear_predict)

linear_error

30121.598183059614

Option B - Gradient Boosting

In [23]:
boosting_model = GradientBoostingRegressor(n_estimators=100, random_state=42)

boosting_model.fit(X_train, y_train)

GradientBoostingRegressor(random_state=42)

In [25]:
boosting_predict = boosting_model.predict(X_test)

boosting_predict

array([ 98226.21419181,  96417.6255735 ,  84453.04910393,  78756.21334096,
        96612.26411679,  94423.59538553, 117645.36980907, 101441.8243224 ,
        94782.55097265,  79064.30134637,  82876.47071533,  77576.21000485,
       109013.27678154, 104883.50025398, 101461.0933942 ,  97384.54940238,
        82401.31066796, 104644.17877114, 103572.73376117,  71282.69294552,
        87928.87261395, 125291.463999  , 100166.90409775,  90928.45817601,
        98392.66590868, 102735.40810932, 103702.3182135 , 117226.8491335 ,
        99829.74396639, 115080.3498961 , 117848.25401778, 101492.29458927,
        91139.09385069,  95944.6022594 , 114809.55631396,  98445.49650768,
       107991.33671141, 104914.9752421 ,  95404.45890103, 109748.95325797,
       107774.14982026,  94883.02821077,  72059.84178554,  93619.71615351,
       100400.96715197, 113630.82651464,  82029.80162654,  78632.30455478,
        88954.36775334, 124438.11441826,  82604.00155669,  94871.04420559,
       117403.17768644, 108719.16572143,  74072.35591228, 108965.14418794,
       111179.51181703, 115139.42155934, 146203.16233287,  79260.32553744,
        96366.20724121,  67378.25393758, 113758.04840005, 101919.71756469,
        71681.85084462])

In [ ]:
boosting_error = mean_absolute_error(y_test, boosting_predict)

boosting_error

30450.205229611038